### ISSUE TITLE
Updates for pyhf

### ISSUE THREAD

**Issue by aperloff** [aperloff/cms-cvmfs-docker#11]
- [x] Make sure `python3` is installed
- [x] Make sure that pip is fully updated
- [x] Tag a release for pyhf usage

**Comment by aperloff** [comment]
Python3 is both installed in the image (`/usr/bin/python3 -> python3.6`) and is setup when sourcing `/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/current/el7-x86_64/setup.sh` (`/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.6/3.6.220616-1/el7-x86_64/usr/bin/python3`). As of this message the latest version of Python is `3.10.5`, but I suppose that will automatically be updated when moving to Centos8.

**Comment by aperloff** [comment]
Will run `/usr/bin/python3 -m pip install --upgrade pip` during image creation.

**Comment by aperloff** [comment]
Will make tags based off of the `master` branch. The first tag will be `pyhf-v0.1.0-beta` (see https://github.com/aperloff/cms-cvmfs-docker/releases/tag/pyhf-v0.1.0-beta). The `beta` part of the flag will be removed once the `pyhf` developers tell me they are happy with the image.

**Comment by aperloff** [comment]
All of the updates specified in this issue have been completed.

**Comment by matthewfeickert** [comment]
@aperloff I can confirm that this image tag works for us, so I think you should be good to make a new tag sans `beta`. Thanks! :rocket:

**Comment by aperloff** [comment]
@matthewfeickert The new tag, `pyhf-v0.1.0`, has been created and the image built (https://hub.docker.com/layers/243817292/aperloff/cms-cvmfs-docker/pyhf-v0.1.0/images/sha256-7c7fc3a944ff9cc357a833a574ba8f9fa57ddc7ff86617b4f0691999c6063856?context=repo).

**Comment by matthewfeickert** [comment]
Fantastic. Thank you @aperloff!
