### ISSUE TITLE
request to install get-sso-cookie pakcage

### ISSUE THREAD

**Issue by hbakhshi** [aperloff/cms-cvmfs-docker#8]
The "cern-get-sso-cookie" package can be helpful to perform some tests. it would be very helpful if this is included in the image

**Comment by aperloff** [comment]
Added cern-get-sso-cookie and the CERN yum repository with https://github.com/aperloff/cms-cvmfs-docker/commit/e76dd2b993788ce606e1da0b03d9af882226c8e3. It is available in the most recent build of the `latest` tag (see [DockerHub](https://hub.docker.com/repository/docker/aperloff/cms-cvmfs-docker/tags?page=1&ordering=last_updated)).

@hbakhshi
